# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Copy Artifacts
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: "deploy.sh"
          strip_components: 1
      # - name: Deploy
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.IP_ADDRESS }}
      #     username: ${{ secrets.USER_NAME }}
      #     port: ${{ secrets.PORT }}
      #     key: ${{ secrets.P_KEY }}
      #     passphrase: ${{ secrets.PASSPHRASE }}
      #     script: bash deploy.sh
